import type { CompanyManifest } from "../../manifest-schema";

/**
 * Apple — clean, minimal, premium.
 * Flawless whitespace, surgical typography, product as hero.
 */
export const manifest: CompanyManifest = {
  slug: "apple",
  name: "Apple",
  description:
    "Clean, minimal, premium. Generous whitespace, surgical typography, and the product as the hero.",
  tagline: "Minimal, premium, product-first with flawless whitespace and surgical typography.",
  bestFor: [
    "apple", "premium", "minimal", "clean", "elegant", "hardware", "device", "phone", "laptop",
    "luxury", "simple", "pro", "tech", "consumer", "store", "product",
  ],
  hueBase: 211,
  radius: { sm: 6, md: 10, lg: 14, xl: 18, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 17, lg: 19, xl: 22, "2xl": 28, "3xl": 34, "4xl": 44 },
  sectionPaddingY: 72,
  sectionGap: 40,
  fonts: { display: "Sora", body: "DM Sans" },
  light: {
    background: "#FFFFFF",
    foreground: "#1D1D1F",
    card: "#FFFFFF",
    cardForeground: "#1D1D1F",
    popover: "#FFFFFF",
    popoverForeground: "#1D1D1F",
    primary: "#0071E3",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F5F7",
    secondaryForeground: "#1D1D1F",
    muted: "#F5F5F7",
    mutedForeground: "#6E6E73",
    accent: "#F5F5F7",
    accentForeground: "#1D1D1F",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    success: "#0F6B36",
    successSubtle: "#E4F1E9",
    warning: "#A04604",
    warningSubtle: "#F7EDE1",
    border: "#D2D2D7",
    input: "#D2D2D7",
    ring: "#0071E3",
    chart: ["#0071E3", "#5AC8FA", "#FF9500", "#34C759", "#AF52DE", "#FF2D55"],
  },
  dark: {
    background: "#000000",
    foreground: "#F5F5F7",
    card: "#1C1C1E",
    cardForeground: "#F5F5F7",
    popover: "#2C2C2E",
    popoverForeground: "#F5F5F7",
    primary: "#0A84FF",
    primaryForeground: "#061E35",
    secondary: "#2C2C2E",
    secondaryForeground: "#F5F5F7",
    muted: "#2C2C2E",
    mutedForeground: "#98989D",
    accent: "#2C2C2E",
    accentForeground: "#F5F5F7",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    success: "#30D158",
    successSubtle: "#1B3324",
    warning: "#FFD60A",
    warningSubtle: "#332B14",
    border: "#3A3A3C",
    input: "#48484A",
    ring: "#0A84FF",
    chart: ["#0A84FF", "#64D2FF", "#FFD60A", "#30D158", "#BF5AF2", "#FF375F"],
  },
  rules: [
    "Whitespace is the design. Let content breathe — generous vertical rhythm, never crammed.",
    "One hero product moment per page; everything else recedes.",
    "Headlines are large, light-weight display type (300–500), tracking-tight, left-aligned.",
    "Cards are --card on --background with a hairline border; never layered colored bands.",
    "The blue primary appears sparingly — links, key CTAs, active states. Max ~4 per screen.",
    "Buttons are capsule-rounded, solid primary or transparent with a hairline border.",
    "No gradients, no decorative blobs, no playful illustration.",
    "Copy is calm and factual: short sentences, no hype, no exclamation marks.",
  ],
  signatureMoves: [
    "Full-width hero with one product image and a headline in very large light type",
    "Feature rows: alternating image and text in a clean 2-col grid",
    "Pricing / spec table as a calm, airy card set",
    "Small 'More' link patterns instead of loud CTA pairs",
    "Footer with many quiet columns and tiny links",
  ],
  avoidPatterns: [
    "colorful gradients", "bordered card grids", "bold black headlines", "emoji",
    "playful illustrations", "crowded density", "centered marketing copy",
  ],
  voiceAndTone:
    "Calm, confident, precise. Short declarative sentences. No exclamation marks, no hype, no superlatives. Name the benefit plainly and let the product speak.",
  screenRecipes: {
    landing: {
      id: "landing", title: "Landing", purpose: "Product-first marketing page",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + quiet links + one outline CTA" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "one product visual + very large headline + one primary CTA" },
        { block: "list", variant: "features", content: "alternating feature rows (image + copy)" },
        { block: "stats", variant: "grid", content: "quiet spec highlights" },
        { block: "cta", variant: "band", content: "final product moment + single CTA" },
        { block: "footer", variant: "columns" },
      ],
      guidance: "Use for consumer-tech, hardware, premium product marketing.",
    },
    catalog: {
      id: "catalog", title: "Catalog", purpose: "Product browse",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + search + cart" },
        { block: "hero", variant: "statement", content: "category headline + blurb" },
        { block: "search", variant: "dropdown", content: "search + one dropdown filter" },
        { block: "list", variant: "cards", emphasis: true, content: "product cards with image + name + price" },
        { block: "footer", variant: "columns" },
      ],
    },
    app_dashboard: {
      id: "app_dashboard", title: "Overview", purpose: "Consumer app dashboard",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "screen title + search + avatar" },
        { block: "hero", variant: "statement", content: "greeting + headline" },
        { block: "stats", variant: "row", emphasis: true, content: "2-3 key metrics" },
        { block: "chart", variant: "area-card", content: "primary trend" },
        { block: "list", variant: "activity", content: "recent activity" },
      ],
    },
    list_detail: {
      id: "list_detail", title: "Library", purpose: "Browse and inspect",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "title + search" },
        { block: "hero", variant: "statement", content: "list title + description" },
        { block: "detail", variant: "pane", emphasis: true, content: "master list + detail panel" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Settings", purpose: "Account management",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "settings title" },
        { block: "hero", variant: "statement", content: "settings headline" },
        { block: "form", variant: "cards", emphasis: true, content: "account + preferences + sign-out" },
      ],
    },
    article: {
      id: "article", title: "Article", purpose: "Long-form editorial",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + quiet links" },
        { block: "hero", variant: "statement", emphasis: true, content: "headline + dek + byline" },
        { block: "list", variant: "rows", content: "supporting media + prose blocks" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "Capsule-shaped (rounded-full), primary solid blue or hairline-bordered neutral. Weight 500, body-size text. No shadows.",
    Card: "White on white, 1px hairline border, radius-lg. Content breathing with 24-32px padding. Never a drop shadow.",
    Input: "Hairline border, radius-md, subtle focus ring in blue. Labels quiet and above the field.",
    Sidebar: "White rail with quiet nav, active item tinted with accent/10 and blue text. Faded 4px radius on hover.",
    Topbar: "White bar, hairline bottom border. Title in large light display type, actions to the right.",
    Table: "Airy — generous row padding, hairline dividers, right-aligned numerics, muted metadata.",
    StatCard: "Label in muted small text, value in large light display type, tiny delta chip.",
    Badge: "Muted neutral pill; success/warning/destructive only for real status.",
    Chart: "Thin area or line on the chart palette, subtle gridlines, faint axis labels.",
    EmptyState: "Centered icon in a muted circle, one-line message, one quiet CTA.",
    Footer: "Multi-column quiet links, tiny type, generous spacing.",
  },
};
