import type { CompanyManifest } from "../../manifest-schema";

/**
 * Stripe — professional, dense, trustworthy.
 * Ink-on-white clarity, the signature indigo/violet accent, professional density.
 */
export const manifest: CompanyManifest = {
  slug: "stripe",
  name: "Stripe",
  description:
    "Professional, dense, trustworthy. Ink-on-white clarity, the signature indigo/violet accent, and high information density done right.",
  tagline: "Professional craft: ink-on-white clarity with the signature indigo accent.",
  bestFor: [
    "stripe", "payments", "finance", "fintech", "banking", "billing", "saas", "dashboard",
    "money", "invoice", "subscription", "analytics", "commerce", "business", "admin",
  ],
  hueBase: 244,
  radius: { sm: 4, md: 6, lg: 10, xl: 14, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 18, xl: 20, "2xl": 24, "3xl": 30, "4xl": 36 },
  sectionPaddingY: 48,
  sectionGap: 28,
  fonts: { display: "Outfit", body: "DM Sans" },
  light: {
    background: "#FFFFFF",
    foreground: "#0A2540",
    card: "#FFFFFF",
    cardForeground: "#0A2540",
    popover: "#FFFFFF",
    popoverForeground: "#0A2540",
    primary: "#635BFF",
    primaryForeground: "#FFFFFF",
    secondary: "#F6F9FC",
    secondaryForeground: "#0A2540",
    muted: "#F6F9FC",
    mutedForeground: "#425466",
    accent: "#635BFF",
    accentForeground: "#FFFFFF",
    destructive: "#EB5757",
    destructiveForeground: "#FFFFFF",
    success: "#0A6F56",
    successSubtle: "#E4F3EF",
    warning: "#8A5300",
    warningSubtle: "#FAF0E0",
    border: "#E3E8EF",
    input: "#C9D0D9",
    ring: "#635BFF",
    chart: ["#635BFF", "#00C48C", "#F2994A", "#EB5757", "#0A2540", "#00A3E0"],
  },
  dark: {
    background: "#0A2540",
    foreground: "#F6F9FC",
    card: "#0E2D4D",
    cardForeground: "#F6F9FC",
    popover: "#14324F",
    popoverForeground: "#F6F9FC",
    primary: "#8B85FF",
    primaryForeground: "#0A2540",
    secondary: "#14324F",
    secondaryForeground: "#F6F9FC",
    muted: "#14324F",
    mutedForeground: "#ADBDCC",
    accent: "#8B85FF",
    accentForeground: "#0A2540",
    destructive: "#FF6B6B",
    destructiveForeground: "#FFFFFF",
    success: "#00D9A6",
    successSubtle: "#14332C",
    warning: "#FFB15C",
    warningSubtle: "#332819",
    border: "#1E3A5F",
    input: "#2A4A6E",
    ring: "#8B85FF",
    chart: ["#8B85FF", "#00D9A6", "#FFB15C", "#FF6B6B", "#F6F9FC", "#00A3E0"],
  },
  rules: [
    "Professional density: information-rich layouts with clear hierarchy — this is a working tool, not a showcase.",
    "Ink is navy (#0A2540) on white; the indigo/violet (#635BFF) accents actions and data marks.",
    "Typography is precise: small-medium body (14-16px), tight tracking, tabular numerals for money.",
    "Cards, tables, and forms share a hairline border language; sharp-ish radii (4-10px).",
    "Dashboards: KPI stat row on top, then dense tables and charts with toolbars.",
    "Buttons are compact; the primary is indigo-filled, secondary is white with a navy border.",
    "Copy is terse and concrete: 'Payment succeeded', '$12,400.00', 'net 30'.",
    "Charts are clean line/area with the indigo primary and subtle grids.",
  ],
  signatureMoves: [
    "KPI stat row (label + big tabular value + delta) above dense data tables",
    "Toolbar + hairline data table with search, filters, and a primary action",
    "Settings: sectioned cards with forms, two-column on desktop",
    "Invoice/receipt-like details: clear line items, right-aligned money, status badges",
    "Contrasting indigo-on-navy dark mode that still feels professional",
  ],
  avoidPatterns: [
    "playful illustration", "rounded pill-heavy friendly UI", "low information density",
    "centered marketing hero on app screens", "bright saturated color blocks", "emoji",
  ],
  voiceAndTone:
    "Terse, precise, trustworthy. Money and numbers are exact ('$1,204.50', 'May 12'). Status is explicit ('Succeeded', 'Requires action'). No fluff, no hype — confidence through clarity.",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Overview", purpose: "Business dashboard",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "workspace + search + notifications + user" },
        { block: "hero", variant: "statement", content: "dashboard title + period selector" },
        { block: "stats", variant: "row", emphasis: true, content: "KPI row: revenue, volume, active customers, success rate" },
        { block: "chart", variant: "area-card", content: "revenue trend" },
        { block: "table", variant: "panel", content: "recent transactions with status badges" },
      ],
    },
    list_detail: {
      id: "list_detail", title: "Customers", purpose: "Customer and invoices",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "title + search + new" },
        { block: "stats", variant: "row", content: "MRR, active customers, churn, success rate" },
        { block: "detail", variant: "pane", emphasis: true, content: "customer list + detail panel (profile, invoices, balance)" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Settings", purpose: "Account and billing",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "settings title" },
        { block: "hero", variant: "statement", content: "workspace + billing headline" },
        { block: "form", variant: "cards", emphasis: true, content: "business details, payout, team, danger zone" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Fintech/developer marketing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav + CTA" },
        { block: "hero", variant: "split", emphasis: true, content: "headline + CTA + product/dashboard visual" },
        { block: "stats", variant: "row", content: "platform proof (volume, uptime, countries)" },
        { block: "list", variant: "features", content: "capabilities, dense and specific" },
        { block: "cta", variant: "band", content: "start integrating" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Products", purpose: "Pricing / catalog",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav + CTA" },
        { block: "pricing", variant: "cards", emphasis: true, content: "pricing cards with feature lists" },
        { block: "list", variant: "rows", content: "FAQ / detailed rates" },
        { block: "cta", variant: "band", content: "contact sales" },
        { block: "footer", variant: "columns" },
      ],
    },
    article: {
      id: "article", title: "Docs", purpose: "Documentation / reference",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "docs title + search" },
        { block: "hero", variant: "statement", content: "guide headline" },
        { block: "detail", variant: "pane", emphasis: true, content: "sidebar nav + code/prose article" },
      ],
    },
  },
  componentGuidance: {
    Button: "Compact, medium weight. Primary: indigo filled. Secondary: white with navy hairline border. Radius 6-8px.",
    Card: "White with hairline border, radius-lg (10px), 16-20px padding. Sectioned headers with hairline dividers.",
    Input: "Hairline border, radius-md (6px), tight focus ring in indigo. Labels small and precise.",
    Sidebar: "White rail, active item = indigo text on indigo/5 with a 2px indigo left indicator.",
    Topbar: "White, hairline bottom border; breadcrumb/title left, actions right.",
    Table: "Dense: 40-48px rows, hairline dividers, right-aligned money in tabular-nums, status badges.",
    StatCard: "Label small muted uppercase, value big tabular, delta chip in success/destructive.",
    Badge: "Flat: success (green) for Succeeded, warning (amber) for Pending, destructive (red) for Failed, neutral otherwise.",
    Chart: "Clean line/area in indigo with subtle gridlines; axis labels small muted.",
    EmptyState: "Compact: title + one line + a primary action. Used for empty tables.",
    Footer: "Dense multi-column with API/status/legal links, professional.",
  },
};
