import type { CompanyManifest } from "../../manifest-schema";

/**
 * Netflix — cinematic, immersive, bold.
 * Dark-first, the signature red, carousel rows, and drama at every scale.
 */
export const manifest: CompanyManifest = {
  slug: "netflix",
  name: "Netflix",
  description:
    "Cinematic, immersive, bold. Dark-first surfaces, the signature red, carousel rows of content, and drama at every scale.",
  tagline: "Cinematic immersion: dark surfaces, signature red, carousel rows.",
  bestFor: [
    "netflix", "movie", "film", "video", "streaming", "tv", "cinema", "entertainment", "series",
    "watch", "cinematic", "drama", "show", "theater", "binge",
  ],
  hueBase: 356,
  radius: { sm: 2, md: 4, lg: 6, xl: 8, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 18, xl: 21, "2xl": 26, "3xl": 34, "4xl": 44 },
  sectionPaddingY: 48,
  sectionGap: 32,
  fonts: { display: "Archivo", body: "DM Sans" },
  light: {
    background: "#FFFFFF",
    foreground: "#141414",
    card: "#FFFFFF",
    cardForeground: "#141414",
    popover: "#FFFFFF",
    popoverForeground: "#141414",
    primary: "#E50914",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F5F5",
    secondaryForeground: "#141414",
    muted: "#F5F5F5",
    mutedForeground: "#555555",
    accent: "#E50914",
    accentForeground: "#FFFFFF",
    destructive: "#E50914",
    destructiveForeground: "#FFFFFF",
    success: "#0B7153",
    successSubtle: "#E7F4EF",
    warning: "#8A6700",
    warningSubtle: "#FAF3DF",
    border: "#E0E0E0",
    input: "#D0D0D0",
    ring: "#E50914",
    chart: ["#E50914", "#141414", "#B20710", "#22A06B", "#F5A623", "#7B61FF"],
  },
  dark: {
    background: "#141414",
    foreground: "#F5F5F5",
    card: "#1F1F1F",
    cardForeground: "#F5F5F5",
    popover: "#262626",
    popoverForeground: "#F5F5F5",
    primary: "#FF1A22",
    primaryForeground: "#1A0002",
    secondary: "#2A2A2A",
    secondaryForeground: "#F5F5F5",
    muted: "#2A2A2A",
    mutedForeground: "#8C8C8C",
    accent: "#E50914",
    accentForeground: "#FFFFFF",
    destructive: "#E50914",
    destructiveForeground: "#FFFFFF",
    success: "#2FB77F",
    successSubtle: "#143025",
    warning: "#F5A623",
    warningSubtle: "#33280F",
    border: "#333333",
    input: "#3D3D3D",
    ring: "#E50914",
    chart: ["#E50914", "#F5F5F5", "#B20710", "#22A06B", "#F5A623", "#7B61FF"],
  },
  rules: [
    "Dark-first immersion: near-black surfaces (#141414), white text, the red (#E50914) for action.",
    "The red is reserved: logo, primary CTAs, and the rare active state. Never paint whole sections red.",
    "Content is organized into horizontal carousel rows with bold section titles — the signature Netflix pattern.",
    "Hero titles are massive (40px+) with a dark gradient overlay and a big 'Play' CTA.",
    "Poster/artwork tiles are 2:3 rectangles; hover shows a slight scale + info overlay.",
    "Typography is bold and cinematic — heavy weights, tight tracking on titles, clean sans throughout.",
    "Keep the canvas dark and uncluttered; drama comes from scale, not color.",
    "Progress bars are thin and red on dark; 'Continue Watching' rows reuse artwork tiles.",
  ],
  signatureMoves: [
    "Hero: full-bleed artwork with a dark gradient + huge title + Play/More Info buttons",
    "Carousel rows: 'Trending Now', 'Top 10', 'New Releases' — each a horizontal strip of poster tiles",
    "Continue Watching row with thin red progress bars under artwork",
    "Profile select: large avatar tiles to choose who's watching",
    "Bold section titles ('Trending Now', 'Only on Netflix') in big white type",
  ],
  avoidPatterns: [
    "light-first layouts", "blue accents", "rounded friendly cards", "gradient color washes outside heroes",
    "busy colorful grids", "cute illustrations", "small timid type",
  ],
  voiceAndTone:
    "Cinematic and confident. Titles are the voice ('Stranger Things', 'Trending Now'). Short, bold, suggestive — let the artwork and scale do the talking.",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Home", purpose: "Streaming home",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "logo + nav + profile" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "featured artwork + huge title + Play" },
        { block: "list", variant: "carousel", content: "'Trending Now' row" },
        { block: "list", variant: "carousel", content: "'Continue Watching' with progress" },
        { block: "list", variant: "carousel", content: "'New Releases' row" },
      ],
      guidance: "Dark streaming/movie/entertainment home with carousel rows.",
    },
    list_detail: {
      id: "list_detail", title: "Detail", purpose: "Movie/show detail",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "logo + back + profile" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "backdrop + title + Play + metadata (year, rating, duration)" },
        { block: "detail", variant: "pane", content: "synopsis + cast + episodes list" },
        { block: "list", variant: "carousel", content: "'More Like This' row" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Streaming signup landing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "logo + sign-in" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "headline + email CTA over dark imagery" },
        { block: "list", variant: "features", content: "enjoy on your TV, download, watch everywhere" },
        { block: "cta", variant: "band", content: "get started" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Browse", purpose: "Browse titles",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "logo + search + profile" },
        { block: "search", variant: "bar", content: "search titles" },
        { block: "list", variant: "cards", emphasis: true, content: "poster tile grid, 2:3 rectangles" },
        { block: "footer", variant: "columns" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Profile", purpose: "Profile and playback",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "back + logo" },
        { block: "hero", variant: "statement", content: "profile avatar + name" },
        { block: "form", variant: "cards", emphasis: true, content: "playback settings, maturity, sign-out" },
      ],
    },
    article: {
      id: "article", title: "Show", purpose: "Title story / editorial",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "logo + links" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "artwork + title + synopsis" },
        { block: "list", variant: "rows", content: "episode/behind-the-scenes rows" },
        { block: "cta", variant: "band", content: "watch now" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "Red filled for primary ('Play', 'Watch'), dark secondary with white border. Rounded-sm (4-6px), bold label.",
    Card: "Dark surface; media cards are 2:3 poster tiles with a hover scale + info overlay. No borders — separation via darkness.",
    Input: "Dark field on dark, hairline border, minimal. Search is large and prominent.",
    Sidebar: "Not typical — use a dark topbar. Profile/menu live in the top-right.",
    Topbar: "Near-black, transparent over hero then solid; logo left, nav + profile right.",
    Table: "Episode lists: number, thumbnail, title, duration, play on hover. Dense but clean.",
    StatCard: "Rare. If used: bold value, muted label, red highlight for active.",
    Badge: "Flat pills: red for 'Top 10'/new, neutral on dark for metadata.",
    Chart: "Thin red line/area on dark; subtle grid.",
    EmptyState: "'Start watching' + a red Play CTA.",
    Footer: "Dark multi-column links, quiet, small type.",
  },
};
