import type { CompanyManifest } from "../../manifest-schema";

/**
 * Duolingo — friendly, confident, playful-but-clean learning.
 * White surfaces, the signature feather green, bold rounded type, soft
 * cards, and a cheerful mascot energy without clutter.
 */
export const manifest: CompanyManifest = {
  slug: "duolingo",
  name: "Duolingo",
  description:
    "Friendly and confident. White surfaces, the signature feather green, bold rounded type, soft cards, and playful-but-clean learning energy.",
  tagline: "Friendly learning: white, feather green, bold rounded type, soft cards.",
  bestFor: [
    "duolingo", "language", "learn", "learning", "lesson", "education", "course", "flashcard",
    "quiz", "study", "student", "school", "tutor", "teaching", "practice", "gamified",
  ],
  hueBase: 120,
  radius: { sm: 8, md: 12, lg: 16, xl: 20, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 19, xl: 23, "2xl": 28, "3xl": 34, "4xl": 42 },
  sectionPaddingY: 56,
  sectionGap: 32,
  fonts: { display: "Nunito", body: "Nunito" },
  light: {
    background: "#FFFFFF",
    foreground: "#3C3C3C",
    card: "#FFFFFF",
    cardForeground: "#3C3C3C",
    popover: "#FFFFFF",
    popoverForeground: "#3C3C3C",
    primary: "#3a8301",
    primaryForeground: "#FFFFFF",
    secondary: "#F2F7F0",
    secondaryForeground: "#3C3C3C",
    muted: "#F4F4F0",
    mutedForeground: "#757575",
    accent: "#3a8301",
    accentForeground: "#FFFFFF",
    destructive: "#EA2B2B",
    destructiveForeground: "#FFFFFF",
    success: "#417a00",
    successSubtle: "#EAF7E0",
    warning: "#a35f00",
    warningSubtle: "#FFF4E0",
    border: "#E5E5E0",
    input: "#DADAD4",
    ring: "#58CC02",
    chart: ["#58CC02", "#1CB0F6", "#FF9600", "#CE82FF", "#EA2B2B", "#4B4B4B"],
  },
  dark: {
    background: "#131F24",
    foreground: "#E8F3EA",
    card: "#1D2A30",
    cardForeground: "#E8F3EA",
    popover: "#24343B",
    popoverForeground: "#E8F3EA",
    primary: "#58CC02",
    primaryForeground: "#131F24",
    secondary: "#233139",
    secondaryForeground: "#E8F3EA",
    muted: "#233139",
    mutedForeground: "#8FA39B",
    accent: "#7ED957",
    accentForeground: "#101810",
    destructive: "#FF4B4B",
    destructiveForeground: "#FFFFFF",
    success: "#58A700",
    successSubtle: "#1B2A16",
    warning: "#FFB224",
    warningSubtle: "#33290F",
    border: "#2E4048",
    input: "#3A4E57",
    ring: "#7ED957",
    chart: ["#7ED957", "#2EB4F6", "#FFB224", "#D29CFF", "#FF5C5C", "#F4F4F4"],
  },
  rules: [
    "Feather green (#58CC02) is THE brand color: primary buttons, progress, success — one confident green on white.",
    "Bold rounded everything: Nunito display, chunky buttons (48px+), generous radius, soft shadows on cards.",
    "White light surfaces; dark mode is a deep green-tinted slate, never pure black.",
    "Playful but clean: mascot energy through color and shape, not clutter or gradients.",
    "Progress is celebrated: streaks, XP, and checkmarks in green with bold numbers.",
    "One strong CTA per screen in green; secondary actions are white buttons with green text.",
    "Copy is short, cheerful, and specific ('5 min a day', 'Streak: 12 days').",
  ],
  signatureMoves: [
    "Giant green 'START' button — the loudest element on the screen",
    "Streak + XP scoreboard: bold tabular counts with green checkmarks",
    "Lesson path / progress units: rounded tiles on a light track",
    "Celebratory success bands: green tonal band with a big check and 'Lesson complete'",
    "Soft white cards with green accents on a light page",
  ],
  avoidPatterns: [
    "serious corporate SaaS", "dark moody themes", "tiny buttons", "muted desaturated greens",
    "dense data tables", "formal typography", "flat gray dashboards",
  ],
  voiceAndTone:
    "Cheerful, short, specific. 'You're 5 min away from your daily goal!' Encouraging but factual — no empty hype, no guilt. Celebrate with words and green.",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Learn", purpose: "Lesson home",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "streak + XP + settings" },
        { block: "hero", variant: "app", emphasis: true, content: "daily goal + START lesson CTA" },
        { block: "list", variant: "cards", content: "lesson path units" },
        { block: "stats", variant: "scoreboard", content: "streak, XP, league" },
      ],
    },
    list_detail: {
      id: "list_detail", title: "Lesson", purpose: "Lesson practice",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "progress + close" },
        { block: "media", variant: "gallery", emphasis: true, content: "lesson imagery/illustration" },
        { block: "detail", variant: "pane", content: "question + choices + one CTA" },
        { block: "cta", variant: "band", content: "check answer / continue" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Profile", purpose: "Learner profile",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "profile title" },
        { block: "hero", variant: "app", content: "learner summary + streak" },
        { block: "form", variant: "cards", emphasis: true, content: "goals, daily reminders, privacy" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Learning app marketing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav + CTA" },
        { block: "hero", variant: "split", emphasis: true, content: "headline + big green CTA + app visual" },
        { block: "list", variant: "features", content: "how it works, cheerful cards" },
        { block: "stats", variant: "scoreboard", content: "learners, courses, ratings" },
        { block: "cta", variant: "band", content: "start free" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Courses", purpose: "Course selection",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search courses" },
        { block: "search", variant: "dropdown", content: "filter by language" },
        { block: "list", variant: "cards", emphasis: true, content: "course cards with progress" },
      ],
    },
    article: {
      id: "article", title: "Blog", purpose: "Learning tips",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav" },
        { block: "hero", variant: "banded", emphasis: true, content: "title on green-tinted band" },
        { block: "detail", variant: "pane", content: "article body" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "Chunky (48–56px) green primary, white bold text, rounded-full; secondary = white with green text + hairline.",
    Card: "White, 16–20px radius, soft shadow; course cards show progress bar + bold title.",
    Input: "White, hairline, 12px radius, 48px; focus = green ring.",
    Sidebar: "White rail with green active fill; user footer with streak.",
    Topbar: "White: streak + XP left, settings right, hairline bottom border.",
    Table: "Avoid tables in-app; if needed, bold rows with green checkmarks.",
    StatCard: "Scoreboard: bold tabular XP/streak with green checkmark chips.",
    Badge: "Green success pills; rounded-full, bold small text.",
    Chart: "Bold rounded bars in green; progress rings for units.",
    EmptyState: "Cheerful: mascot-adjacent illustration, one green CTA.",
    Footer: "White with link columns and the green logo mark.",
  },
};
