export interface BrandKit {
  colors: Record<string, string>;
  fonts: Record<string, string>;
  sizes: Record<string, string>;
  radius: Record<string, string>;
  shadows?: Record<string, string>;
}

// ── Pipeline phases (wire contract — hardcoded in the client UI) ────────────

export type PastelPhase =
  | "brief"
  | "plan"
  | "review"
  | "build"
  | "verify"
  | "present";

export const PHASE_ORDER: PastelPhase[] = ["brief", "plan", "review", "build", "verify", "present"];

export type PhaseStatus = "idle" | "running" | "done" | "error";

// ── Run kinds ───────────────────────────────────────────────────────────────

/** "full" = whole pipeline; "delta" = add screen(s) onto an existing project state. */
export type RunKind = "full" | "delta";

// ── SSE events (wire contract — do not extend without a client change) ──────

export interface PastelEvent {
  /** phase | title | doc | file | activity | done | error */
  type:
    | "phase"
    | "title"
    | "doc"
    | "file"
    | "activity"
    | "done"
    | "error";
  phase?: PastelPhase;
  status?: PhaseStatus;
  message?: string;
  /** doc events */
  doc?: { path: string; title: string; kind: string; content: string };
  /** file events */
  file?: { path: string; kind: string; content: string };
  /** title events */
  title?: string;
  /** done event result */
  result?: unknown;
}

// ── Derived sitemap (computed deterministically from the product spec) ───────

export interface SitemapScreen {
  id: string;
  name: string;
  purpose: string;
  sections: string[];
  components: string[];
}

export interface Sitemap {
  screens: SitemapScreen[];
  components: string[];
}

// ── Run transparency (persisted in the manifest; the client ignores these) ──

export interface CostLedgerEntry {
  stage: string;
  modelId: string;
  inputChars: number;
  outputChars: number;
  credits: number;
}

export interface RunCostSummary {
  entries: CostLedgerEntry[];
  totalCredits: number;
  totalDollars: number;
}

export interface RegistryStats {
  /** registry components reused without a model call */
  reused: number;
  /** components generated by a model call this run */
  generated: number;
  /** components that fell back to the deterministic template */
  fallback: number;
}

export interface RunQualityStats {
  /** total surgical repair calls issued across all stages */
  repairs: number;
  /** design gate first-pass (no findings) */
  gatePassedFirstTry: boolean;
}

export interface AgentManifest {
  screens: string[];
  docs: string[];
  brandKit: BrandKit | null;
  styleSeed: string | null;
  phases: Record<string, PhaseStatus>;
  /** screens that failed verification after all fix rounds */
  failedScreens: string[];
  /** v2 additions — optional, additive, client ignores them */
  runKind?: RunKind;
  costs?: RunCostSummary;
  registryStats?: RegistryStats;
  quality?: RunQualityStats;
  /** delta runs: screens added by this run */
  screensAdded?: string[];
  /** stage 11: how the pattern set was sourced */
  patternRetrieval?: { provider: "pgvector" | "static"; count: number };
  /** stage 17: repair-loop iterations used and final pass state */
  repairLoop?: { iterations: number; passed: boolean };
}

export interface GeneratedFile {
  path: string;
  kind: "screen" | "component" | "style" | "entry";
  content: string;
}

export type StyleSeed = {
  name: string;
  mood: string[];
  spatialPhilosophy: string;
  typographicAttitude: string;
  colorTemperature: string;
  textureApproach: string;
  creativeDirection: string;
};
