import type { CompanyManifest } from "../../manifest-schema";

/**
 * Uber — utilitarian, bold, effortless movement.
 * Map-first, high-contrast black + green, bottom-sheet interactions.
 */
export const manifest: CompanyManifest = {
  slug: "uber",
  name: "Uber",
  description:
    "Utilitarian and bold. Map-first layouts, high-contrast black + green, and bottom-sheet interactions that feel like effortless movement.",
  tagline: "Utilitarian mobility: map-first, black + green, bottom-sheet ease.",
  bestFor: [
    "uber", "ride", "transport", "mobility", "delivery", "food", "courier", "logistics",
    "taxi", "driving", "eats", "grocery", "location", "map", "booking", "travel",
  ],
  hueBase: 152,
  radius: { sm: 4, md: 8, lg: 14, xl: 20, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 18, xl: 20, "2xl": 26, "3xl": 32, "4xl": 40 },
  sectionPaddingY: 56,
  sectionGap: 28,
  fonts: { display: "Space Grotesk", body: "Space Grotesk" },
  light: {
    background: "#FFFFFF",
    foreground: "#000000",
    card: "#FFFFFF",
    cardForeground: "#000000",
    popover: "#FFFFFF",
    popoverForeground: "#000000",
    primary: "#000000",
    primaryForeground: "#FFFFFF",
    secondary: "#F6F6F6",
    secondaryForeground: "#000000",
    muted: "#F6F6F6",
    mutedForeground: "#545454",
    accent: "#06C167",
    accentForeground: "#000000",
    destructive: "#DA291C",
    destructiveForeground: "#FFFFFF",
    success: "#0A7A42",
    successSubtle: "#E7F6EE",
    warning: "#9A5B00",
    warningSubtle: "#FBF1E2",
    border: "#E6E6E6",
    input: "#D9D9D9",
    ring: "#000000",
    chart: ["#000000", "#06C167", "#FF8B00", "#7B61FF", "#DA291C", "#00C0FF"],
  },
  dark: {
    background: "#141414",
    foreground: "#FFFFFF",
    card: "#1D1D1D",
    cardForeground: "#FFFFFF",
    popover: "#232323",
    popoverForeground: "#FFFFFF",
    primary: "#FFFFFF",
    primaryForeground: "#000000",
    secondary: "#2B2B2B",
    secondaryForeground: "#FFFFFF",
    muted: "#2B2B2B",
    mutedForeground: "#9A9A9A",
    accent: "#06C167",
    accentForeground: "#000000",
    destructive: "#FF4A3D",
    destructiveForeground: "#FFFFFF",
    success: "#06C167",
    successSubtle: "#173324",
    warning: "#FFA01A",
    warningSubtle: "#33260F",
    border: "#333333",
    input: "#3D3D3D",
    ring: "#FFFFFF",
    chart: ["#FFFFFF", "#06C167", "#FFA01A", "#7B61FF", "#FF4A3D", "#00C0FF"],
  },
  rules: [
    "Utilitarian clarity: high-contrast black (or white on dark), a single green accent for actions.",
    "Map-first for location products: the map is the hero, controls float on top, info in cards.",
    "Bottom-sheet pattern: primary info and actions live in rounded-top cards docked to the bottom.",
    "Buttons are solid black with white text (or inverted on dark); green is reserved for the ONE primary action.",
    "Typography is clean and geometric; labels are terse and functional ('PICKUP', 'ETA 3 MIN').",
    "Cards are flat with hairline borders; radius is generous on interactive sheets (xl).",
    "Use large, readable prices and times — this is a transaction UI.",
    "No decorative illustration; icons are minimal and functional.",
  ],
  signatureMoves: [
    "Map-first home: full-bleed map with a floating search bar and bottom summary card",
    "Bottom sheet: rounded-top card docked to screen bottom holding options + a single green CTA",
    "Trip/order cards: destination, price, ETA, and status in one dense readable row",
    "Two-tone hero: dark top bar with a bright green primary action",
    "Live status timeline with clear states (requested → driver → arriving)",
  ],
  avoidPatterns: [
    "colorful playful illustrations", "soft pastels", "heavy marketing copy", "gradients",
    "cluttered dense tables", "decorative flourish", "ambiguous pricing",
  ],
  voiceAndTone:
    "Terse, functional, reassuring. Time and money are always concrete ('Arriving in 3 min', '$14.20'). Address the user by destination, not by identity. Zero marketing fluff.",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Home", purpose: "Map-first request/order home",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "location + profile" },
        { block: "hero", variant: "map", emphasis: true, content: "full-bleed map + floating search" },
        { block: "detail", variant: "bottom", content: "bottom sheet: pickup/dropoff options + green CTA" },
      ],
      guidance: "Map-first home with a bottom action sheet — the core Uber pattern.",
    },
    list_detail: {
      id: "list_detail", title: "Activity", purpose: "Past trips and orders",
      nav: "tabbar",
      blocks: [
        { block: "topbar", variant: "app", content: "activity title" },
        { block: "search", variant: "bar", content: "search trips" },
        { block: "detail", variant: "pane", emphasis: true, content: "trip list + detail panel with route, fare, status" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Profile", purpose: "Account and payment",
      nav: "tabbar",
      blocks: [
        { block: "topbar", variant: "app", content: "profile title" },
        { block: "detail", variant: "pane", content: "account header + saved places" },
        { block: "form", variant: "cards", emphasis: true, content: "payment methods, preferences, safety" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Product/regional landing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + sign-in + CTA" },
        { block: "hero", variant: "split", emphasis: true, content: "headline + CTA + map/product visual" },
        { block: "stats", variant: "row", content: "proof metrics (riders, cities, ETA)" },
        { block: "list", variant: "features", content: "how it works steps" },
        { block: "cta", variant: "band", content: "download / get started" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Eats", purpose: "Restaurant / store browse",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + search + cart" },
        { block: "search", variant: "bar", content: "deliver to + search + filter chips" },
        { block: "list", variant: "cards", emphasis: true, content: "restaurant cards with photo, rating, ETA" },
        { block: "footer", variant: "columns" },
      ],
    },
    article: {
      id: "article", title: "Info", purpose: "Help / how it works",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + links" },
        { block: "hero", variant: "statement", emphasis: true, content: "topic headline + intro" },
        { block: "list", variant: "rows", content: "faq / steps" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "Solid black, white label, radius-md, medium-heavy weight. The single green variant is reserved for the one primary action per screen.",
    Card: "Flat white with hairline border; bottom sheets and summary cards use radius-xl on top corners.",
    Input: "Contained field with a subtle border; search bars are rounded-full with an icon.",
    Sidebar: "Not typical — use topbar/tabbar. If used, a clean white rail with black active items.",
    Topbar: "Terse: location/status left, profile right. Bold but compact.",
    Table: "Dense readable rows: destination, fare, ETA, status. Right-aligned prices in tabular-nums.",
    StatCard: "Big bold number (500-700), terse label, no decorations.",
    Badge: "Flat pills: black, white, or green. Status only when meaningful.",
    Chart: "Line/area in black or green, minimal grid, clear axis.",
    EmptyState: "Minimal: 'No trips yet' + one functional CTA.",
    Footer: "Compact multi-column links, quiet.",
  },
};
