import type { CompanyManifest } from "../../manifest-schema";

/**
 * Notion — calm, editorial, focused.
 * Warm monochrome, clean typography, generous whitespace, quiet structure.
 */
export const manifest: CompanyManifest = {
  slug: "notion",
  name: "Notion",
  description:
    "Calm, editorial, focused. Warm monochrome surfaces, clean typography, generous whitespace, and quiet, flexible structure.",
  tagline: "Calm editorial workspace: warm monochrome, clean type, quiet structure.",
  bestFor: [
    "notion", "productivity", "notes", "docs", "wiki", "knowledge", "workspace", "project",
    "planning", "organize", "journal", "team", "collaboration", "writing", "editorial",
  ],
  hueBase: 34,
  radius: { sm: 2, md: 4, lg: 6, xl: 8, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 18, xl: 21, "2xl": 26, "3xl": 30, "4xl": 34 },
  sectionPaddingY: 48,
  sectionGap: 28,
  fonts: { display: "Figtree", body: "Figtree" },
  light: {
    background: "#FFFFFF",
    foreground: "#37352F",
    card: "#FFFFFF",
    cardForeground: "#37352F",
    popover: "#FFFFFF",
    popoverForeground: "#37352F",
    primary: "#37352F",
    primaryForeground: "#FFFFFF",
    secondary: "#F7F6F3",
    secondaryForeground: "#37352F",
    muted: "#F7F6F3",
    mutedForeground: "#6E6B66",
    accent: "#1B6DC2",
    accentForeground: "#FFFFFF",
    destructive: "#D44C47",
    destructiveForeground: "#FFFFFF",
    success: "#0B7153",
    successSubtle: "#E7F4EF",
    warning: "#8A6700",
    warningSubtle: "#FAF3DF",
    border: "#E9E9E7",
    input: "#D3D1CB",
    ring: "#37352F",
    chart: ["#37352F", "#2383E2", "#0F8B5F", "#DFAB01", "#D44C47", "#6B6B6B"],
  },
  dark: {
    background: "#191919",
    foreground: "#E6E5E1",
    card: "#202020",
    cardForeground: "#E6E5E1",
    popover: "#262626",
    popoverForeground: "#E6E5E1",
    primary: "#FFFFFF",
    primaryForeground: "#191919",
    secondary: "#2C2C2C",
    secondaryForeground: "#E6E5E1",
    muted: "#2C2C2C",
    mutedForeground: "#9B9A97",
    accent: "#2568AC",
    accentForeground: "#FFFFFF",
    destructive: "#FF7369",
    destructiveForeground: "#FFFFFF",
    success: "#4FC08A",
    successSubtle: "#16301F",
    warning: "#D9A84E",
    warningSubtle: "#332A14",
    border: "#333333",
    input: "#404040",
    ring: "#FFFFFF",
    chart: ["#FFFFFF", "#5199F0", "#46A06B", "#D9A84E", "#FF7369", "#8A8A8A"],
  },
  rules: [
    "Calm monochrome first: warm whites and grays, one restrained blue accent for interactive highlights.",
    "Editorial typography: clean sans, comfortable leading, generous margins; content is the interface.",
    "Structure is quiet — hairline dividers, dotted lines, collapsible sections; nothing shouts.",
    "Cards and pages are white/paper-like with minimal borders; hover reveals controls.",
    "The blue accent is for links, active states, and the rare primary action. Everything else is ink-on-paper.",
    "Density is comfortable and readable; whitespace is generous; text-heavy screens are normal.",
    "Interactive affordances appear on hover (edit, add, more) — the canvas stays clean.",
    "Copy is plain-spoken and useful; no marketing tone inside the product.",
  ],
  signatureMoves: [
    "Left sidebar with pages/nav tree; main pane is one long, calm document",
    "Document pages: big title, breadcrumb, blocks of text, toggles, quiet metadata",
    "Database views: table/list/board with inline edit affordances",
    "Empty states that invite creation: '+ New page', 'Start writing'",
    "Hairline-divided workspaces with generous paper-like whitespace",
  ],
  avoidPatterns: [
    "loud gradients", "dense card grids", "bold saturated color blocks", "centered marketing type",
    "overwrought buttons", "playful illustrations", "cramped density",
  ],
  voiceAndTone:
    "Plain-spoken, calm, useful. 'Write, plan, collaborate.' Direct and unpretentious — the interface disappears and the content leads. Invite action quietly ('New page', 'Add a comment').",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Workspace", purpose: "Team workspace home",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search + breadcrumb + user" },
        { block: "hero", variant: "statement", content: "workspace headline + create CTA" },
        { block: "list", variant: "cards", emphasis: true, content: "recent pages, quiet cards" },
        { block: "table", variant: "panel", content: "shared database view" },
        { block: "list", variant: "activity", content: "recent updates" },
      ],
    },
    list_detail: {
      id: "list_detail", title: "Pages", purpose: "Documents and databases",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search + breadcrumb" },
        { block: "hero", variant: "statement", content: "page title + metadata" },
        { block: "detail", variant: "pane", emphasis: true, content: "document blocks / database rows" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Settings", purpose: "Account and workspace",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "settings title" },
        { block: "hero", variant: "statement", content: "workspace headline" },
        { block: "form", variant: "cards", emphasis: true, content: "account, notifications, workspace, members" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Productivity product marketing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav + CTA" },
        { block: "hero", variant: "split", emphasis: true, content: "headline + CTA + product screenshot" },
        { block: "list", variant: "features", content: "use cases, calm rows" },
        { block: "stats", variant: "row", content: "community proof" },
        { block: "cta", variant: "band", content: "get started free" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Templates", purpose: "Template gallery",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + search" },
        { block: "search", variant: "bar", content: "search templates" },
        { block: "list", variant: "cards", emphasis: true, content: "template cards, minimal" },
        { block: "footer", variant: "columns" },
      ],
    },
    article: {
      id: "article", title: "Document", purpose: "Long-form document",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "breadcrumb + share" },
        { block: "hero", variant: "statement", emphasis: true, content: "title + subtext + author row" },
        { block: "detail", variant: "pane", content: "document prose with headings and toggles" },
      ],
    },
  },
  componentGuidance: {
    Button: "Quiet: white or muted with ink text; primary uses ink fill rarely. Small radius, medium weight, hover shows a faint fill.",
    Card: "Paper-like: near-white, 1px hairline, tiny radius (6-8px), generous padding. Hover shows a subtle 'edit' affordance.",
    Input: "Bare: no visible border until focus, or a very light border; ink-on-paper feel.",
    Sidebar: "Left rail of pages: muted nav tree, active page = ink text on muted, chevron toggles.",
    Topbar: "Minimal: breadcrumb/title left, search + share + user right, hairline bottom border.",
    Table: "Database style: clean rows, muted metadata, inline edit on hover, sortable headers.",
    StatCard: "Quiet: label muted, value ink, no decorations; used sparingly.",
    Badge: "Neutral text pill on muted; color only for real status.",
    Chart: "Minimal line/bar in ink or blue, no heavy chrome.",
    EmptyState: "'+ New page' style invitation: a single centered quiet action.",
    Footer: "Simple: a few link columns, quiet.",
  },
};
