import type { CompanyManifest } from "../../manifest-schema";

/**
 * Airbnb — warm, friendly, trust-building.
 * Soft coral, generous whitespace, photo-first listings, human warmth.
 */
export const manifest: CompanyManifest = {
  slug: "airbnb",
  name: "Airbnb",
  description:
    "Warm, friendly, trust-building. Soft coral accents, generous whitespace, and photo-first listings with a human touch.",
  tagline: "Warm hospitality: coral accents, photo-first listings, human trust.",
  bestFor: [
    "airbnb", "travel", "booking", "stay", "hotel", "vacation", "host", "rental", "trip",
    "lodging", "home", "marketplace", "community", "experience",
  ],
  hueBase: 350,
  radius: { sm: 8, md: 12, lg: 16, xl: 20, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 18, xl: 21, "2xl": 26, "3xl": 32, "4xl": 38 },
  sectionPaddingY: 56,
  sectionGap: 32,
  fonts: { display: "Plus Jakarta Sans", body: "Plus Jakarta Sans" },
  light: {
    background: "#FFFFFF",
    foreground: "#222222",
    card: "#FFFFFF",
    cardForeground: "#222222",
    popover: "#FFFFFF",
    popoverForeground: "#222222",
    primary: "#C62B4F",
    primaryForeground: "#FFFFFF",
    secondary: "#F7F7F7",
    secondaryForeground: "#222222",
    muted: "#F7F7F7",
    mutedForeground: "#717171",
    accent: "#C62B4F",
    accentForeground: "#FFFFFF",
    destructive: "#C13515",
    destructiveForeground: "#FFFFFF",
    success: "#0B7153",
    successSubtle: "#E7F4EF",
    warning: "#8A6700",
    warningSubtle: "#FAF3DF",
    border: "#DDDDDD",
    input: "#DDDDDD",
    ring: "#FF385C",
    chart: ["#FF385C", "#00A87A", "#6A4DE8", "#FFB400", "#E31C5F", "#1E96B7"],
  },
  dark: {
    background: "#1A1A1A",
    foreground: "#F7F7F7",
    card: "#222222",
    cardForeground: "#F7F7F7",
    popover: "#2A2A2A",
    popoverForeground: "#F7F7F7",
    primary: "#E84A62",
    primaryForeground: "#2A0A14",
    secondary: "#2C2C2C",
    secondaryForeground: "#F7F7F7",
    muted: "#2C2C2C",
    mutedForeground: "#B0B0B0",
    accent: "#E84A62",
    accentForeground: "#2A0A14",
    destructive: "#E5484D",
    destructiveForeground: "#FFFFFF",
    success: "#2FB77F",
    successSubtle: "#143025",
    warning: "#F5A623",
    warningSubtle: "#33280F",
    border: "#3A3A3A",
    input: "#444444",
    ring: "#FF5A5F",
    chart: ["#FF5A5F", "#22A06B", "#8A7DFF", "#F5A623", "#E5484D", "#3FC0DB"],
  },
  rules: [
    "Warmth and trust: soft coral accents on a white canvas, human photos everywhere.",
    "Photo-first listings — the image is the card's hero; details below in quiet type.",
    "Generous whitespace; rounded corners everywhere (16-20px) for a friendly feel.",
    "Buttons: solid coral primary, pill-shaped; secondary is a hairline 'Airbnb-style' outline.",
    "Reviews/social proof are prominent: stars, counts, host avatars.",
    "Copy is warm, personal, and specific to the stay ('Entire home · 3 beds · Superhost').",
    "Trust signals are visible: ratings, verified badges, cancellation policy.",
    "Density is comfortable — never crowded. Each listing breathes.",
  ],
  signatureMoves: [
    "Search hero: 'Where to?' + pill search filters + date/guest fields",
    "Photo-first listing cards with a heart/save toggle and price + rating row",
    "Host profile with avatar, superhost badge, review count, response time",
    "Tabs for stays/experiences/location with smooth pill toggles",
    "Trust footer: support, community, hosting links in many columns",
  ],
  avoidPatterns: [
    "cold corporate density", "sharp corners", "harsh high-contrast type", "dark-first themes",
    "faceless stock icons everywhere", "hard-sell CTAs", "generic gray SaaS layouts",
  ],
  voiceAndTone:
    "Warm, personal, reassuring. 'Book unique homes and experiences.' Be specific and human — mention hosts, neighborhoods, ratings. Friendly but not chatty.",
  screenRecipes: {
    landing: {
      id: "landing", title: "Landing", purpose: "Booking/hospitality marketing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + search + sign-in" },
        { block: "hero", variant: "split", emphasis: true, content: "'Where to?' search hero + destination visual" },
        { block: "list", variant: "cards", content: "featured stays, photo-first" },
        { block: "stats", variant: "row", content: "community proof (homes, guests, countries)" },
        { block: "cta", variant: "band", content: "become a host / start exploring" },
        { block: "footer", variant: "columns" },
      ],
      guidance: "Use for travel, booking, marketplace, community products.",
    },
    catalog: {
      id: "catalog", title: "Stays", purpose: "Browse listings",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + search + filters" },
        { block: "search", variant: "filters", content: "pill filter row (price, type, rating)" },
        { block: "list", variant: "cards", emphasis: true, content: "photo-first listing cards with rating + price" },
        { block: "footer", variant: "columns" },
      ],
    },
    list_detail: {
      id: "list_detail", title: "Listing", purpose: "Listing detail",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + share/save" },
        { block: "media", variant: "gallery", emphasis: true, content: "photo gallery of the stay" },
        { block: "detail", variant: "pane", content: "title + host + amenities + reviews" },
        { block: "cta", variant: "band", content: "booking summary card with price + dates" },
        { block: "footer", variant: "columns" },
      ],
    },
    app_dashboard: {
      id: "app_dashboard", title: "Home", purpose: "Guest/owner hub",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "hello + search" },
        { block: "hero", variant: "statement", content: "welcome headline" },
        { block: "stats", variant: "row", emphasis: true, content: "upcoming trips / earnings / reviews" },
        { block: "list", variant: "cards", content: "upcoming trips, photo-first" },
        { block: "list", variant: "activity", content: "recent messages" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Account", purpose: "Profile and payments",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "account title" },
        { block: "detail", variant: "pane", content: "profile header with avatar + verified badge" },
        { block: "form", variant: "cards", emphasis: true, content: "payments, notifications, privacy" },
      ],
    },
    article: {
      id: "article", title: "Guide", purpose: "Travel guide / editorial",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + links" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "destination image + headline + dek" },
        { block: "list", variant: "rows", content: "guide prose + photo rows" },
        { block: "cta", variant: "band", content: "explore more stays" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "Pill (rounded-full), solid coral primary; secondary is a white/hairline 'Airbnb' outline. Medium weight.",
    Card: "Rounded-2xl (20px), white with hairline border, photo top. Generous 16-20px padding around content.",
    Input: "Rounded-md with subtle border; search fields are pill-shaped with icons.",
    Sidebar: "White rail, active item is coral text on coral/10; rounded hover.",
    Topbar: "White, hairline bottom border, centered brand + pill search + profile.",
    Table: "Comfortable rows, generous padding, subtle dividers, muted secondary text.",
    StatCard: "Label muted, value 500-weight, coral delta when positive.",
    Badge: "Soft pills: coral/10 with coral text for highlights; neutral for metadata.",
    Chart: "Soft area chart in coral, minimal grid, rounded feel.",
    EmptyState: "Friendly: illustration-ish icon, warm message, one coral CTA.",
    Footer: "Many columns of warm links, community + support emphasis.",
  },
};
