import type { CompanyManifest } from "../../manifest-schema";

/**
 * Linear — crisp, dense, developer-grade focus.
 * Monochrome surface, hairline dividers, small precise type, one restrained
 * indigo accent, keyboard-first density.
 */
export const manifest: CompanyManifest = {
  slug: "linear",
  name: "Linear",
  description:
    "Crisp, dense, developer-grade. Monochrome surfaces, hairline dividers, small precise type, and one restrained indigo accent for the primary action.",
  tagline: "Crisp issue tracking: tight density, hairline dividers, indigo primary.",
  bestFor: [
    "linear", "issue", "bug", "sprint", "backlog", "dev tool", "developer", "engineering",
    "software", "roadmap", "kanban", "startup", "tracker", "cycle", "product management",
  ],
  hueBase: 231,
  radius: { sm: 3, md: 5, lg: 7, xl: 9, full: 9999 },
  typeScale: { xs: 11.5, sm: 13, base: 14, lg: 16, xl: 19, "2xl": 23, "3xl": 27, "4xl": 32 },
  sectionPaddingY: 48,
  sectionGap: 28,
  fonts: { display: "Inter", body: "Inter", mono: "JetBrains Mono" },
  light: {
    background: "#FFFFFF",
    foreground: "#1A1C1E",
    card: "#FFFFFF",
    cardForeground: "#1A1C1E",
    popover: "#FFFFFF",
    popoverForeground: "#1A1C1E",
    primary: "#5E6AD2",
    primaryForeground: "#FFFFFF",
    secondary: "#F7F8F9",
    secondaryForeground: "#1A1C1E",
    muted: "#F7F8F9",
    mutedForeground: "#6E7074",
    accent: "#5E6AD2",
    accentForeground: "#FFFFFF",
    destructive: "#E5484D",
    destructiveForeground: "#FFFFFF",
    success: "#357e42",
    successSubtle: "#EFF6EF",
    warning: "#996300",
    warningSubtle: "#FFF7E5",
    border: "#E7E8EA",
    input: "#D4D6D8",
    ring: "#5E6AD2",
    chart: ["#5E6AD2", "#46A758", "#FFB224", "#E5484D", "#0091FF", "#8E4EC6"],
  },
  dark: {
    background: "#0E0F11",
    foreground: "#E9EAEC",
    card: "#17181A",
    cardForeground: "#E9EAEC",
    popover: "#1E1F21",
    popoverForeground: "#E9EAEC",
    primary: "#7B86E8",
    primaryForeground: "#0E0F11",
    secondary: "#242528",
    secondaryForeground: "#E9EAEC",
    muted: "#242528",
    mutedForeground: "#8C8F94",
    accent: "#5c6ae6",
    accentForeground: "#FFFFFF",
    destructive: "#E5484D",
    destructiveForeground: "#FFFFFF",
    success: "#46A758",
    successSubtle: "#16231A",
    warning: "#F5A524",
    warningSubtle: "#2E2410",
    border: "#2A2C30",
    input: "#3A3D42",
    ring: "#6E7BE8",
    chart: ["#6E7BE8", "#46A758", "#F5A524", "#E5484D", "#0091FF", "#8E4EC6"],
  },
  rules: [
    "Dense and precise: small type, tight rows, hairline dividers — density is the brand.",
    "Monochrome first: white/ink surfaces, one indigo accent reserved for the primary action and active states.",
    "Surfaces are flat: cards barely exist; lists divide with hairlines, not boxes.",
    "Small type everywhere (13–14px body), high information density, tabular numerics for counts.",
    "Bold hierarchy through WEIGHT and SIZE, never color noise.",
    "Interactions are instant and subtle: quick hovers, no bouncy animation.",
    "Empty states are useful, not cute: a short line and one clear action.",
  ],
  signatureMoves: [
    "Sidebar with keyboard-shortcut hints; the primary button is indigo on white",
    "Issue list: dense rows with ID, title, status pill, assignee, and priority icon",
    "Cycle board: compact kanban columns with story-point totals in the header",
    "Keyboard-first shortcuts visibly surfaced in menus and placeholders",
    "Tabular count chips and status pills with precise tones",
  ],
  avoidPatterns: [
    "large rounded cards", "gradients", "playful illustration", "oversized marketing type",
    "warm colors", "centered layouts", "bouncy animation", "big empty whitespace",
  ],
  voiceAndTone:
    "Terse, precise, confident. 'Resolve the noise.' Developer tone: short sentences, exact numbers, no hype. Buttons say exactly what they do ('Archive', 'Move to done').",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Inbox", purpose: "Assigned issues across teams",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search + new issue" },
        { block: "hero", variant: "app", emphasis: true, content: "counts + primary CTA" },
        { block: "list", variant: "rows", content: "issue rows, dense divided list" },
        { block: "table", variant: "panel", content: "issue table with status columns" },
      ],
    },
    list_detail: {
      id: "list_detail", title: "Issue", purpose: "Single issue view",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "breadcrumb + search" },
        { block: "detail", variant: "pane", emphasis: true, content: "issue title, description, metadata, comments" },
        { block: "list", variant: "activity", content: "issue activity timeline" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Settings", purpose: "Workspace settings",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "settings title" },
        { block: "hero", variant: "app", content: "workspace summary + counts" },
        { block: "form", variant: "cards", emphasis: true, content: "team, members, workflow, labels" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Developer tool marketing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav + CTA" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "headline + CTA on dark band" },
        { block: "list", variant: "features", content: "tight feature rows" },
        { block: "cta", variant: "band", content: "try Linear" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Projects", purpose: "Project list",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search + new project" },
        { block: "search", variant: "dropdown", content: "filter projects" },
        { block: "list", variant: "rows", emphasis: true, content: "project rows with progress" },
      ],
    },
    article: {
      id: "article", title: "Changelog", purpose: "Release notes",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav" },
        { block: "hero", variant: "statement", emphasis: true, content: "release title + date" },
        { block: "detail", variant: "pane", content: "changelog sections" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "Compact (32–40px), indigo primary, white text; secondary is ghost with hairline border. Small radius, sharp edges.",
    Card: "Used rarely: white with a hairline border, near-zero radius, tight padding. Lists beat cards.",
    Input: "Small (32–36px), hairline border, mono optional for IDs; focus = indigo ring.",
    Sidebar: "Left rail: tiny nav rows with shortcut hints, active = muted fill + ink text.",
    Topbar: "Dense: search placeholder 'Search or jump to…', user + settings right, hairline bottom border.",
    Table: "Issue table: dense rows, ID in mono, status pills, right-aligned counts, sticky header.",
    StatCard: "Rare: label muted small, value ink bold, delta chip; used for cycle progress.",
    Badge: "Status pills with precise tones (success/warning/destructive), small and tight.",
    Chart: "Minimal area/line in indigo or mono-style grid; used for cycle reports.",
    EmptyState: "One short line + one primary action; no illustration.",
    Footer: "Simple quiet link columns.",
  },
};
