/**
 * Deterministic mock-content generator — Pastel v7 (domain-aware).
 *
 * v6 fed every screen from a SaaS/B2B generator (companies, MRR, invoices,
 * "deployed to production"), so a fitness app shipped with "Aperture AI" and
 * "$22,091" invoices. v7 selects a DOMAIN PACK from the brief (fitness,
 * ecommerce, media, social, productivity, travel, finance) and generates
 * product-relevant data by construction: workouts have distances and paces,
 * shops have products and prices, music has titles and plays.
 *
 * All data derives from a seed (brief + run id hash) — reproducible across
 * runs, repair cycles, and reference rendering.
 */

import { mulberry32, hashSeed, pickDomain, domainPeople, briefText, REVIEW_PHRASES, REVIEW_HEADING, TRUST_ITEMS, DOMAIN_PRIMARY_CTA, DOMAIN_HOME_CTA, PRICE_SUFFIX, type BriefLike } from "./domains";

export interface Person {
  name: string;
  role: string;
  email: string;
  initials: string;
  /** Hue for avatar tint (0-360). */
  hue: number;
}

export interface Metric {
  label: string;
  unit: string;
  value: string;
  delta: number;
  positive: boolean;
  note: string;
  spark: number[];
}

export interface Series {
  label: string;
  unit: string;
  points: Array<{ x: string; y: number }>;
}

export interface TableRow {
  id: string;
  name: string;
  detail: string;
  amount: string;
  status: string;
  date: string;
  owner: string;
  /** V9: per-item detail-pane values aligned with `detailFields` (coherent
   * with the row's own data — a listing can never contradict its card). */
  fields?: string[];
  /** V11: the item's own booking window + guest count (stay/travel). */
  dates?: string;
  guests?: string;
}

export interface SettingsSection {
  title: string;
  items: Array<{ label: string; value: string; control: "toggle" | "select" | "text" }>;
}

/** V14: social-proof entry — the DATA agent writes these per run; the
 * deterministic fallback derives them from the domain packs. */
export interface ReviewEntry {
  name: string;
  initials: string;
  hue: number;
  rating: number;
  text: string;
}

export interface MockDataset {
  seed: number;
  /** Domain pack slug that generated this data ("fitness", "ecommerce", …). */
  domain: string;
  /** V12 distinguishes an adaptive strength dashboard from a legacy running catalog. */
  strengthMode?: boolean;
  /** V15: the media SUBJECT the run's imagery is about (scene families key).
   * The data agent writes it; the fallback derives it from the domain pack. */
  mediaSubject?: string;
  people: Person[];
  metrics: Metric[];
  series: Series[];
  rows: TableRow[];
  activity: string[];
  detailFields: string[];
  /** Display values for the detail pane, aligned with detailFields. */
  detailValues: string[];
  settingsSections: SettingsSection[];
  searchPlaceholder: string;
  emptyTitle: string;
  emptyBody: string;
  /** V14: page content generated by the DATA agent (fallback fills from the
   * domain packs) — the composer reads THESE instead of baked consts. */
  reviews: ReviewEntry[];
  reviewHeading: string;
  trustItems: string[];
  primaryCta: string;
  homeCta: string;
  priceSuffix?: string;
}

export { mulberry32, hashSeed, pickDomain, briefText };
export type { BriefLike };

/** V15: default media subject per domain pack (scene families key). The
 * data agent may override with a product-specific subject. */
export const SUBJECT_OF_DOMAIN: Record<string, string> = {
  fitness: "runner",
  ecommerce: "product",
  media: "album",
  social: "chat",
  productivity: "board",
  rentals: "house",
  travel: "house",
  finance: "graph",
};

/** Normalize a unit string for comparison: lowercase, no spaces, and "·"
 * treated the same as "/" (min·km ≡ min/km). */
export function normalizeUnit(u: string | undefined | null): string {
  return (u ?? "").toLowerCase().trim().replace(/[·]/g, "/").replace(/\s+/g, "");
}

export function mockDataset(input: string | BriefLike, seedInput?: string): MockDataset {
  const brief: BriefLike = typeof input === "string" ? { productType: "product", description: input } : input;
  const seed = hashSeed(`${seedInput ?? briefText(brief)}`);
  const rnd = mulberry32(seed);
  const pack = pickDomain(briefText(brief));
  const strengthMode = pack.slug === "fitness" && /adaptive|personal trainer|suggested load|form cue|readiness|recovery block/i.test(briefText(brief));

  const people = domainPeople(rnd);
  const items = pack.items(rnd);
  const owners = people.map((p) => p.name);

  const rows: TableRow[] = items.map((it, i) => ({
    id: it.id,
    name: it.name,
    detail: it.detail,
    amount: it.amount,
    status: it.status,
    date: it.date,
    owner: owners[i % owners.length],
    fields: it.fields,
    dates: it.dates,
    guests: it.guests,
  }));

  // V14: the fallback dataset fills the page-content slots from the domain
  // packs (reviews, heading, trust items, CTAs, price suffix) so the
  // composer has a complete content layer even when the data agent falls
  // back deterministically.
  const phrases = REVIEW_PHRASES[pack.slug] ?? REVIEW_PHRASES.travel;
  const reviews: ReviewEntry[] = people.slice(0, 6).map((p, i) => ({
    name: p.name,
    initials: p.initials,
    hue: p.hue,
    rating: 4 + (i % 5) * 0.2,
    text: phrases[i % phrases.length],
  }));

  return {
    seed,
    domain: pack.slug,
    strengthMode,
    mediaSubject: SUBJECT_OF_DOMAIN[pack.slug] ?? "generic",
    people,
    metrics: pack.metrics(rnd),
    series: pack.series(rnd),
    rows,
    activity: pack.activity(rnd),
    detailFields: pack.detailFields(),
    detailValues: pack.detailValues(rnd),
    settingsSections: pack.settingsSections(),
    searchPlaceholder: pack.searchPlaceholder(),
    emptyTitle: pack.emptyTitle(),
    emptyBody: pack.emptyBody(),
    reviews,
    reviewHeading: REVIEW_HEADING[pack.slug] ?? "What people say",
    trustItems: TRUST_ITEMS[pack.slug] ?? TRUST_ITEMS.travel,
    primaryCta: DOMAIN_PRIMARY_CTA[pack.slug] ?? "Continue",
    homeCta: DOMAIN_HOME_CTA[pack.slug] ?? "Get started",
    priceSuffix: PRICE_SUFFIX[pack.slug],
  };
}

// ── Dataset slice helpers (used by builder prompts) ──────────────────────

export function datasetPrompt(ds: MockDataset): string {
  const p = (x: Person) => `${x.name} (${x.role})`;
  const s = (x: SettingsSection) =>
    `${x.title}: ${x.items.map((i) => `${i.label} = ${i.value} [${i.control}]`).join("; ")}`;
  return [
    `PRODUCT DATA (domain pack: "${ds.domain}") — use this data to fill the component's data-driven slots (metrics, items, people, activity). NEVER invent other-domain content (no invoices, no company names, no currency) unless the product is financial/shopping.`,
    "",
    `People: ${ds.people.map(p).join("; ")}`,
    "",
    "Metrics:",
    ...ds.metrics.map((m) => `- ${m.label}: ${m.value} ${m.unit} (${m.positive ? "+" : ""}${m.delta}% ${m.note})`),
    "",
    "Time series:",
    ...ds.series.map((s2) => `- ${s2.label}: ${s2.points.slice(0, 12).map((pt) => `${pt.x}=${s2.unit}${pt.y}`).join(", ")}`),
    "",
    "Items (first 5):",
    ...ds.rows.slice(0, 5).map((r) => `- ${r.id} ${r.name} (${r.detail}) ${r.amount} — ${r.status} — ${r.date}`),
    "",
    `Recent activity: ${ds.activity.slice(0, 5).join("; ")}`,
    "",
    `Settings sections: ${ds.settingsSections.map(s).join(" | ")}`,
  ].join("\n");
}
