import type { CompanyManifest } from "../../manifest-schema";

/**
 * Spotify — bold, dark, immersive.
 * Dark-first surfaces, the signature green, and media rows/carousels of content.
 */
export const manifest: CompanyManifest = {
  slug: "spotify",
  name: "Spotify",
  description:
    "Bold, dark, immersive. Dark-first surfaces, the signature green accent, and rich media rows and carousels.",
  tagline: "Bold and dark: immersive surfaces, signature green, media-forward content.",
  bestFor: [
    "spotify", "music", "audio", "podcast", "streaming", "entertainment", "media", "playlist",
    "listen", "radio", "dj", "creator", "song", "album",
  ],
  hueBase: 141,
  radius: { sm: 6, md: 10, lg: 14, xl: 18, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 18, xl: 21, "2xl": 26, "3xl": 32, "4xl": 40 },
  sectionPaddingY: 56,
  sectionGap: 32,
  fonts: { display: "Manrope", body: "Manrope" },
  light: {
    background: "#FFFFFF",
    foreground: "#191414",
    card: "#FFFFFF",
    cardForeground: "#191414",
    popover: "#FFFFFF",
    popoverForeground: "#191414",
    primary: "#0F7A3E",
    primaryForeground: "#FFFFFF",
    secondary: "#F3F3F3",
    secondaryForeground: "#191414",
    muted: "#F3F3F3",
    mutedForeground: "#6B6B6B",
    accent: "#1DB954",
    accentForeground: "#000000",
    destructive: "#E91429",
    destructiveForeground: "#FFFFFF",
    success: "#0B6E3A",
    successSubtle: "#E4F1E9",
    warning: "#8A5D00",
    warningSubtle: "#FAF3DF",
    border: "#E3E3E3",
    input: "#D6D6D6",
    ring: "#1DB954",
    chart: ["#1DB954", "#191414", "#7B61FF", "#F59E0B", "#E91429", "#00C0FF"],
  },
  dark: {
    background: "#121212",
    foreground: "#FFFFFF",
    card: "#181818",
    cardForeground: "#FFFFFF",
    popover: "#242424",
    popoverForeground: "#FFFFFF",
    primary: "#1DB954",
    primaryForeground: "#000000",
    secondary: "#242424",
    secondaryForeground: "#FFFFFF",
    muted: "#242424",
    mutedForeground: "#B3B3B3",
    accent: "#1DB954",
    accentForeground: "#000000",
    destructive: "#F15E6C",
    destructiveForeground: "#FFFFFF",
    success: "#1DB954",
    successSubtle: "#173324",
    warning: "#F59E0B",
    warningSubtle: "#33280F",
    border: "#2E2E2E",
    input: "#3A3A3A",
    ring: "#1DB954",
    chart: ["#1DB954", "#FFFFFF", "#7B61FF", "#F59E0B", "#F15E6C", "#00C0FF"],
  },
  rules: [
    "Dark-first: surfaces are near-black (#121212 base, #181818 cards), text is white.",
    "The green (#1DB954) is the brand's voice — used for play buttons, active states, and ONE primary action per screen.",
    "Media is king: album/podcast artwork as square cards and horizontal carousel rows.",
    "Content rows are labeled with bold section headings; scroll horizontally for more.",
    "Cards are compact squares or rectangles with a subtle hover lift and a play button that appears on hover.",
    "Typography is bold and clear — section titles 600-800 weight, clean sans.",
    "Buttons: rounded-full pills, solid green for play, transparent/white-border for ghost actions.",
    "Never busy: plenty of dark breathing room; the green is used surgically.",
  ],
  signatureMoves: [
    "Left sidebar: playlists nav with your library, then content rows in the main pane",
    "Horizontal carousel rows: 'Made For You', 'Recently Played', each card a square artwork tile",
    "Now-playing bar across the bottom with artwork, track, and playback controls",
    "Giant green circular play button on hero/featured content",
    "Dark hero with a gradient wash from the artwork color into the dark background",
  ],
  avoidPatterns: [
    "light-first busy layouts", "coral/red accents", "bordered gray card grids", "tiny thin type",
    "centered everything", "cluttered metadata", "multiple competing CTAs",
  ],
  voiceAndTone:
    "Confident and casual. 'Made for you', 'Discover weekly'. Short labels, bold section headers, and a warm familiarity. Green is the action color; the music does the talking.",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Home", purpose: "Media home / discover",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "greeting + profile" },
        { block: "hero", variant: "banded", emphasis: true, content: "featured content with big play button" },
        { block: "list", variant: "carousel", content: "'Recently played' row of artwork tiles" },
        { block: "list", variant: "carousel", content: "'Made for you' row" },
        { block: "list", variant: "activity", content: "recently played with track + artist" },
      ],
      guidance: "Dark media dashboard with a left library sidebar and carousel rows.",
    },
    list_detail: {
      id: "list_detail", title: "Playlist", purpose: "Playlist / album detail",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "back + search + profile" },
        { block: "hero", variant: "banded", emphasis: true, content: "artwork + title + play button + metadata" },
        { block: "detail", variant: "pane", content: "track list with duration + like" },
        { block: "list", variant: "activity", content: "artist recommendations" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Settings", purpose: "Account and playback",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "settings title" },
        { block: "detail", variant: "pane", content: "account header + plan" },
        { block: "form", variant: "cards", emphasis: true, content: "playback, notifications, privacy, sign-out" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Streaming product landing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + sign-up + CTA" },
        { block: "hero", variant: "banded", emphasis: true, content: "headline + green CTA + product visual" },
        { block: "list", variant: "features", content: "why it's worth it, bold rows" },
        { block: "pricing", variant: "cards", content: "plan cards with green current plan" },
        { block: "cta", variant: "band", content: "get started" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Browse", purpose: "Browse content",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search + profile" },
        { block: "search", variant: "dropdown", content: "search + one dropdown filter" },
        { block: "list", variant: "carousel", emphasis: true, content: "genre/artist tiles, bold labeled rows" },
        { block: "list", variant: "rows", content: "top results list" },
      ],
    },
    article: {
      id: "article", title: "Show", purpose: "Podcast episode",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "back + share" },
        { block: "hero", variant: "banded", emphasis: true, content: "show artwork + title + subscribe" },
        { block: "detail", variant: "pane", content: "episode list with play buttons" },
        { block: "list", variant: "activity", content: "about the show" },
      ],
    },
  },
  componentGuidance: {
    Button: "Rounded-full pills. Green filled = play/primary. White or border-only = ghost/secondary. Bold label.",
    Card: "Dark surface (--card) with radius-lg. Media cards are square artwork tiles with a hover play button.",
    Input: "Rounded-full dark field with subtle border; search is prominent and centered.",
    Sidebar: "Dark rail with library nav; active item highlighted with white text on muted surface.",
    Topbar: "Dark, minimal; bold title + profile. Media controls float on hover.",
    Table: "Track-list style: index/artwork, name (bold), artist (muted), duration, right-aligned actions.",
    StatCard: "Bold value with a muted label; used sparingly (monthly listeners, saves).",
    Badge: "Green pill for premium/active; muted neutral pill otherwise.",
    Chart: "Area in green on dark; subtle grid; trend readable at a glance.",
    EmptyState: "'Nothing here yet' + a green 'Find something to play' CTA.",
    Footer: "Many columns of links on dark; brand wordmark big.",
  },
};
