import type { CompanyManifest } from "../../manifest-schema";

/**
 * Figma — collaborative, precise, design-tool clean.
 * Light gray workspace, white panels, the signature Figma blue, tight
 * hairlines, and layered surfaces with subtle elevation.
 */
export const manifest: CompanyManifest = {
  slug: "figma",
  name: "Figma",
  description:
    "Collaborative and precise. A light gray canvas, white floating panels, the signature Figma blue, tight hairlines, and layered surfaces with subtle elevation.",
  tagline: "Design-tool precision: light gray canvas, white panels, Figma blue accents.",
  bestFor: [
    "figma", "design", "designer", "prototype", "prototyping", "wireframe", "mockup",
    "ui design", "ux design", "creative", "canvas", "board", "collaboration", "design tool",
    "assets", "component library",
  ],
  hueBase: 207,
  radius: { sm: 4, md: 6, lg: 10, xl: 14, full: 9999 },
  typeScale: { xs: 12, sm: 13.5, base: 15, lg: 17, xl: 20, "2xl": 24, "3xl": 30, "4xl": 36 },
  sectionPaddingY: 48,
  sectionGap: 28,
  fonts: { display: "Inter", body: "Inter" },
  light: {
    background: "#FFFFFF",
    foreground: "#242424",
    card: "#FFFFFF",
    cardForeground: "#242424",
    popover: "#FFFFFF",
    popoverForeground: "#242424",
    primary: "#0077cc",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F5F5",
    secondaryForeground: "#242424",
    muted: "#F5F5F5",
    mutedForeground: "#757575",
    accent: "#0077cc",
    accentForeground: "#FFFFFF",
    destructive: "#F24822",
    destructiveForeground: "#FFFFFF",
    success: "#117e50",
    successSubtle: "#E6F7F0",
    warning: "#8f6d00",
    warningSubtle: "#FFF9E0",
    border: "#E2E2E2",
    input: "#CCCCCC",
    ring: "#0D99FF",
    chart: ["#0D99FF", "#1BC47D", "#FFCD29", "#F24822", "#A259FF", "#242424"],
  },
  dark: {
    background: "#1E1E1E",
    foreground: "#F5F5F5",
    card: "#2C2C2C",
    cardForeground: "#F5F5F5",
    popover: "#333333",
    popoverForeground: "#F5F5F5",
    primary: "#0D99FF",
    primaryForeground: "#1E1E1E",
    secondary: "#333333",
    secondaryForeground: "#F5F5F5",
    muted: "#333333",
    mutedForeground: "#A8A8A8",
    accent: "#3DB2FF",
    accentForeground: "#0A0A0A",
    destructive: "#F24822",
    destructiveForeground: "#FFFFFF",
    success: "#1BC47D",
    successSubtle: "#12352A",
    warning: "#E5A50A",
    warningSubtle: "#3A2E0E",
    border: "#444444",
    input: "#555555",
    ring: "#3DB2FF",
    chart: ["#3DB2FF", "#2BD98F", "#E5A50A", "#FF6B4A", "#C88BFF", "#F5F5F5"],
  },
  rules: [
    "The canvas is light gray; content lives on WHITE floating panels with subtle elevation — never cards on white-on-white.",
    "Figma blue (#0D99FF) is the interaction color: links, primary actions, selection, active tabs.",
    "Precision over decoration: tight hairlines, small type, exact alignment, minimal radius (4–10px).",
    "Layered surfaces: white panels on a gray workspace read as depth without shadows.",
    "Density is comfortable: 40px controls, 13–15px type, clear 8px rhythm.",
    "Multi-edit feels alive: cursors/avatars as small presence chips; collaboration is shown, not hidden.",
    "Copy is short and functional; the tool stays out of the way.",
  ],
  signatureMoves: [
    "White panels floating on a gray canvas — the 'workspace' shell",
    "Figma-blue primary button and active tab underline",
    "Layer/asset lists as dense divided rows with tiny icons",
    "Presence avatars stacked on the topbar (collaboration)",
    "Inspect-style stat rows: label left, mono-ish value right, hairline divided",
  ],
  avoidPatterns: [
    "warm palettes", "heavy shadows", "rounded friendly cards on white", "playful illustrations",
    "oversized marketing type", "gradient buttons", "dark canvases",
  ],
  voiceAndTone:
    "Precise, functional, confident. 'Bring ideas to life.' Short action labels ('Share', 'Add comment'), exact counts, no fluff.",
  screenRecipes: {
    app_dashboard: {
      id: "app_dashboard", title: "Files", purpose: "Design file browser",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search files + new file" },
        { block: "hero", variant: "app", emphasis: true, content: "recent files + import CTA" },
        { block: "search", variant: "dropdown", content: "filter by team/project" },
        { block: "list", variant: "cards", content: "file cards with canvas previews" },
      ],
    },
    list_detail: {
      id: "list_detail", title: "Canvas", purpose: "Design canvas",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "file name + presence + share" },
        { block: "media", variant: "gallery", emphasis: true, content: "canvas preview tiles" },
        { block: "detail", variant: "pane", content: "inspector: props, layout, style rows" },
        { block: "list", variant: "activity", content: "recent edits and comments" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Settings", purpose: "Account and team settings",
      nav: "sidebar+topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "settings title" },
        { block: "hero", variant: "app", content: "workspace summary + seat counts" },
        { block: "form", variant: "cards", emphasis: true, content: "account, notifications, team, billing" },
      ],
    },
    landing: {
      id: "landing", title: "Landing", purpose: "Design tool marketing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav + CTA" },
        { block: "hero", variant: "split", emphasis: true, content: "headline + CTA + product visual" },
        { block: "list", variant: "features", content: "collaboration features" },
        { block: "stats", variant: "row", content: "community proof" },
        { block: "cta", variant: "band", content: "try Figma free" },
        { block: "footer", variant: "columns" },
      ],
    },
    catalog: {
      id: "catalog", title: "Community", purpose: "Design asset gallery",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "app", content: "search assets" },
        { block: "search", variant: "dropdown", content: "filter by type" },
        { block: "list", variant: "cards", emphasis: true, content: "asset cards with previews" },
      ],
    },
    article: {
      id: "article", title: "Blog", purpose: "Design stories",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + nav" },
        { block: "hero", variant: "banded", emphasis: true, content: "title on light band" },
        { block: "detail", variant: "pane", content: "article body" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "40px, Figma-blue primary; secondary = white with hairline border; small radius (6px).",
    Card: "White panel, hairline border or subtle elevation, 6–10px radius; works on gray canvas.",
    Input: "40px, hairline border, 6px radius; focus = blue ring.",
    Sidebar: "White rail: nav rows with blue active fill/underline, team section.",
    Topbar: "White: file name left, presence avatars center-right, Share (blue) far right, hairline bottom border.",
    Table: "Asset/property tables: dense rows, mono values, hairline dividers.",
    StatCard: "Inspect-style: label muted left, value right; used for layer/asset counts.",
    Badge: "Small neutral pills; blue for selection, tones for status.",
    Chart: "Minimal area/bar in blue with faint gridlines.",
    EmptyState: "Canvas-like: light dashed frame + one blue CTA ('New file').",
    Footer: "White with link columns and the multicolor logo mark.",
  },
};
