import type { CompanyManifest } from "../../manifest-schema";

/**
 * Nike — bold, athletic, energizing.
 * High-contrast, confident type, product/performance in motion.
 */
export const manifest: CompanyManifest = {
  slug: "nike",
  name: "Nike",
  description:
    "Bold, athletic, energizing. High-contrast color, confident condensed type, and products in motion.",
  tagline: "Bold athletic energy: high contrast, condensed type, products in motion.",
  bestFor: [
    "nike", "sport", "fitness", "athletic", "training", "workout", "run", "running", "gym",
    "wellness", "health", "active", "coach", "challenge", "streak", "marathon", "footwear", "apparel", "energy",
  ],
  hueBase: 72,
  radius: { sm: 4, md: 8, lg: 12, xl: 16, full: 9999 },
  typeScale: { xs: 12, sm: 14, base: 16, lg: 18, xl: 21, "2xl": 26, "3xl": 34, "4xl": 44 },
  sectionPaddingY: 64,
  sectionGap: 32,
  fonts: { display: "Archivo", body: "DM Sans" },
  light: {
    background: "#FFFFFF",
    foreground: "#111111",
    card: "#FFFFFF",
    cardForeground: "#111111",
    popover: "#FFFFFF",
    popoverForeground: "#111111",
    primary: "#111111",
    primaryForeground: "#FFFFFF",
    secondary: "#F4F4F4",
    secondaryForeground: "#111111",
    muted: "#F4F4F4",
    mutedForeground: "#6B6B6B",
    accent: "#EAFF6A",
    accentForeground: "#111111",
    destructive: "#E5383B",
    destructiveForeground: "#FFFFFF",
    success: "#0F6B36",
    successSubtle: "#E4F1E9",
    warning: "#A04604",
    warningSubtle: "#F7EDE1",
    border: "#E4E4E4",
    input: "#CCCCCC",
    ring: "#111111",
    chart: ["#111111", "#EAFF6A", "#FF6D00", "#00B662", "#4C00FF", "#FF007A"],
  },
  dark: {
    background: "#111111",
    foreground: "#F5F5F5",
    card: "#1A1A1A",
    cardForeground: "#F5F5F5",
    popover: "#222222",
    popoverForeground: "#F5F5F5",
    primary: "#EAFF6A",
    primaryForeground: "#111111",
    secondary: "#222222",
    secondaryForeground: "#F5F5F5",
    muted: "#222222",
    mutedForeground: "#9C9C9C",
    accent: "#2A2A2A",
    accentForeground: "#EAFF6A",
    destructive: "#FF4D4D",
    destructiveForeground: "#111111",
    success: "#4ADE80",
    successSubtle: "#17301F",
    warning: "#FBBF24",
    warningSubtle: "#33270D",
    border: "#2E2E2E",
    input: "#3A3A3A",
    ring: "#EAFF6A",
    chart: ["#EAFF6A", "#FF8A00", "#00D46A", "#4C00FF", "#FF4D4D", "#F5F5F5"],
  },
  rules: [
    "High contrast is the identity: black text on white, volt/safety accents, no gray mush.",
    "Headlines are condensed, heavy (700–900), uppercase where the moment is a statement.",
    "One bold accent color (volt, orange, or pink) per screen — used for the hero moment and CTAs.",
    "Products are shown large and in motion; images bleed to edges (full-bleed) on hero sections.",
    "Buttons are bold — filled black (or accent) with heavy-weight labels, never ghost-gray.",
    "Stats feel like scoreboards: big tabular numbers with unit labels, delta chips in accent.",
    "Cards are minimal with a hairline border; avoid soft pastel fills.",
    "Copy is motivational but concrete: distance, reps, pace, calories. No hype clichés.",
  ],
  signatureMoves: [
    "Full-bleed athletic hero: a person mid-motion + a huge condensed headline overlaying",
    "Scoreboard stat row: giant tabular metrics (km, pace, streak) with accent deltas",
    "Challenge/streak cards with progress rings or bars in accent",
    "Product cards in a tight grid with image-first, bold name + price",
    "Big single-word slogans as section headings ('PUSH', 'FASTER')",
  ],
  avoidPatterns: [
    "soft pastels", "rounded friendly cards", "gentle gradients", "light-weight thin type",
    "low-contrast gray-on-gray", "playful illustrations", "corporate speak",
  ],
  voiceAndTone:
    "Motivational, direct, confident. Short punchy sentences. Concrete athletic metrics everywhere. You push, you measure, you improve. No empty hype — prove it with numbers.",
  screenRecipes: {
    landing: {
      id: "landing", title: "Landing", purpose: "Athletic brand landing",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "bold brand + links + accent CTA" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "athlete in motion + huge condensed headline + one CTA" },
        { block: "stats", variant: "scoreboard", content: "scoreboard metrics (distance, pace, streak)" },
        { block: "list", variant: "cards", content: "product/campaign cards, image-first" },
        { block: "cta", variant: "slogan", content: "single-word statement + start CTA" },
        { block: "footer", variant: "columns" },
      ],
      guidance: "Use for fitness, sport, training, wellness products.",
    },
    app_dashboard: {
      id: "app_dashboard", title: "Home", purpose: "Fitness training dashboard",
      nav: "tabbar",
      blocks: [
        { block: "topbar", variant: "app", content: "greeting + streak + avatar" },
        { block: "hero", variant: "statement", content: "today's workout headline + start CTA" },
        { block: "stats", variant: "scoreboard", emphasis: true, content: "km / pace / calories / streak" },
        { block: "chart", variant: "area-card", content: "weekly activity trend" },
        { block: "list", variant: "activity", content: "recent runs/workouts with metrics" },
      ],
      guidance: "Tab-bar mobile-first app shell with scoreboard stats.",
    },
    list_detail: {
      id: "list_detail", title: "Workouts", purpose: "Browse and start workouts",
      nav: "tabbar",
      blocks: [
        { block: "topbar", variant: "app", content: "workouts title + filter" },
        { block: "search", variant: "dropdown", content: "search + one dropdown filter" },
        { block: "detail", variant: "pane", emphasis: true, content: "workout list + detail panel with stats and start CTA" },
      ],
    },
    settings_forms: {
      id: "settings_forms", title: "Profile", purpose: "Athlete profile and goals",
      nav: "tabbar",
      blocks: [
        { block: "topbar", variant: "app", content: "profile title" },
        { block: "detail", variant: "pane", emphasis: true, content: "athlete header (photo, name, PRs) + goal settings" },
        { block: "form", variant: "cards", content: "goal + units + notifications" },
      ],
    },
    catalog: {
      id: "catalog", title: "Shop", purpose: "Product browse",
      nav: "topbar",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + search + cart" },
        { block: "hero", variant: "banded", content: "collection drop banner" },
        { block: "list", variant: "cards", emphasis: true, content: "product grid, image-first, name + price" },
        { block: "footer", variant: "columns" },
      ],
    },
    article: {
      id: "article", title: "Story", purpose: "Brand / athlete story",
      nav: "none",
      blocks: [
        { block: "topbar", variant: "marketing", content: "brand + links" },
        { block: "hero", variant: "fullbleed", emphasis: true, content: "athlete image + pull-quote headline" },
        { block: "list", variant: "rows", content: "story prose blocks" },
        { block: "cta", variant: "band", content: "join/start CTA" },
        { block: "footer", variant: "columns" },
      ],
    },
  },
  componentGuidance: {
    Button: "Bold and chunky: filled black or accent, heavy (700) label, uppercase for statements, radius-lg. Full-width on mobile.",
    Card: "Hairline border, minimal padding around media. Product cards: image first, then bold name + price.",
    Input: "Sharp-ish (radius-md), 1.5px border, bold label. Focus ring in black.",
    Sidebar: "Black rail with white text; active item inverted (white on accent).",
    Topbar: "High-contrast: dark text on white, bold brand wordmark, accent highlight on active nav.",
    Table: "Scoreboard feel: big tabular numbers, right-aligned, accent delta chips.",
    StatCard: "Giant value in display font (700), unit label in muted small text, delta chip in accent.",
    Badge: "Flat pills: black/white or accent. Status tones only when real (streak, PR, done).",
    Chart: "Bold area or bars in a single accent color, high-contrast gridlines.",
    EmptyState: "Statement: 'No runs yet' + a single bold start CTA.",
    Footer: "Black band with white bold links, big brand wordmark.",
  },
};
